import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:alviora_app/screens/call_screen.dart';
import 'firebase_options.dart'; // Generated by flutterfire CLI

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Initialize Firebase
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  // Enable persistence only for web platform
  if (Firebase.apps.isNotEmpty && const bool.fromEnvironment('dart.vm.product') == false) {
    try {
      await FirebaseFirestore.instance.enablePersistence(
        const PersistenceSettings(synchronizeTabs: true),
      );
    } catch (e) {
      print('Persistence not supported on this platform: $e');
    }
  }

  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Alviora Video Call',
      theme: ThemeData.dark(),
      home: const CallScreen(),
    );
  }
}
