// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRBrQlWOWxn-Vnd05il-cTGJyXcwvpcKA',
    appId: '1:577187412387:web:4cc31a5871590a8f6f0216',
    messagingSenderId: '577187412387',
    projectId: 'alviora-10650',
    authDomain: 'alviora-10650.firebaseapp.com',
    databaseURL: 'https://alviora-10650-default-rtdb.firebaseio.com',
    storageBucket: 'alviora-10650.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDC7tJe1wmBGXwQEkTnSejAPf8o2bpZcY8',
    appId: '1:577187412387:android:4d6fbbf7336a328f6f0216',
    messagingSenderId: '577187412387',
    projectId: 'alviora-10650',
    databaseURL: 'https://alviora-10650-default-rtdb.firebaseio.com',
    storageBucket: 'alviora-10650.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZOgZRixdOmsUj3HdZaA4WXe1N77vIxXY',
    appId: '1:577187412387:ios:37b27c8e5e17dfdf6f0216',
    messagingSenderId: '577187412387',
    projectId: 'alviora-10650',
    databaseURL: 'https://alviora-10650-default-rtdb.firebaseio.com',
    storageBucket: 'alviora-10650.firebasestorage.app',
    iosBundleId: 'com.example.alvioraApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZOgZRixdOmsUj3HdZaA4WXe1N77vIxXY',
    appId: '1:577187412387:ios:37b27c8e5e17dfdf6f0216',
    messagingSenderId: '577187412387',
    projectId: 'alviora-10650',
    databaseURL: 'https://alviora-10650-default-rtdb.firebaseio.com',
    storageBucket: 'alviora-10650.firebasestorage.app',
    iosBundleId: 'com.example.alvioraApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRBrQlWOWxn-Vnd05il-cTGJyXcwvpcKA',
    appId: '1:577187412387:web:0efd56b09c426bab6f0216',
    messagingSenderId: '577187412387',
    projectId: 'alviora-10650',
    authDomain: 'alviora-10650.firebaseapp.com',
    databaseURL: 'https://alviora-10650-default-rtdb.firebaseio.com',
    storageBucket: 'alviora-10650.firebasestorage.app',
  );
}
